HelloMvc/Controllers/EmployeesController.cs
using HelloMvc.Models;
using HelloMvc.Models.VM;
using HelloMvc.Repos;
using Microsoft.AspNetCore.Mvc;

namespace HelloMvc.Controllers {
    public class EmployeesController : Controller {
        private readonly IEmployeeRepo _employeeRepo;
        //public static EmployeeMockRepo _employeeRepo =new EmployeeMockRepo() ;

        public EmployeesController(IEmployeeRepo employeeRepo) {
            _employeeRepo = employeeRepo;
        }


        public IActionResult Index()
        {
            
            var employeeData = _employeeRepo.GetAllEmployees();
            return View(employeeData);
        }

        public IActionResult Create() {

            return View();
        }

        [HttpPost]
        public IActionResult Create(EmployeeVm model) {
            //var errorList = new List<string>();

            //if (string.IsNullOrEmpty(model.FirstName)) {
            //    errorList.Add("Invalid First Name"); ;
            //}

            //if (string.IsNullOrEmpty(model.LastName)) {
            //    errorList.Add("Invalid Last Name"); ;
            //}

            //if (errorList.Any()) {
            //    ViewBag.ErrorList = errorList;
            //    return View(model);
            //}


            //1. Add Properties to Employee -> HomePhone and MobilePhone
            //2. Add Properties to EmployeeVm -> HomePhone and MobilePhone
            //3. Add-Migration
            //4. Update-Database
            //4.5 Update Mapping Logic between Employee and EmployeeVM
            //5. Add Validation Logic


            if (string.IsNullOrEmpty(model.HomePhone) && string.IsNullOrEmpty(model.MobilePhone)) {

                ModelState.AddModelError("", "Home phone or Mobile phone required ");
            }


            if (ModelState.IsValid) {
                var entity = new Employee() {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    HomePhone = model.HomePhone,
                    MobilePhone = model.MobilePhone
                };
                _employeeRepo.CreateEmployee(entity);
                return RedirectToAction("Index");
            }

            return View(model);
        }


        public IActionResult Edit(int id) {
            if (id == 0) {
                return RedirectToAction("Index");
            }

            var employee = _employeeRepo.GetById(id);

            return View(employee);
        }

        [HttpPost]
        public IActionResult Edit(Employee model) {
            //_employeeRepo.Update(model);
            return RedirectToAction("Index");
        }
    }
}

HelloMvc/Controllers/VacationsController.cs
using HelloMvc.Models;
using HelloMvc.Repos;
using Microsoft.AspNetCore.Mvc;

namespace HelloMvc.Controllers {
    public class VacationsController : Controller {
        private readonly IEmployeeRepo _employeeRepo;

        //public static EmployeeMockRepo _employeeRepo = new EmployeeMockRepo();
        public VacationsController(IEmployeeRepo employeeRepo) {
            _employeeRepo = employeeRepo;
        }
        public IActionResult Index(int employeeId) {
            if (employeeId == 0) {
                return RedirectToAction("Index", "Employees");
            }


            //var vacations = _employeeRepo.EmployeeVacationsRetrieve(employeeId);
            var vm = _employeeRepo.GetById(employeeId);
            return View(vm);
        }

        public IActionResult Create(int employeeId) {
            var vm = new VacationRequest() { EmployeeId = employeeId, 
                StartDate = DateTime.Today.AddMonths(1),
                EndDate = DateTime.Today.AddMonths(1).AddDays(2),

            };
            return View(vm);

        }

        [HttpPost]
        public IActionResult Create(VacationRequest model)
        {
            _employeeRepo.VacationsRequestCreate(model);
            return RedirectToAction("Index", new {employeeId = model.EmployeeId});

        }

        public IActionResult Delete(int id) {
            var vr = _employeeRepo.VacationsRequestRetrieveById(id);
            return View(vr);
        }
        [HttpPost]
        public IActionResult Delete(VacationRequest model) {
            var vr = _employeeRepo.VacationsRequestDelete(model.VacationRequestId, model.EmployeeId);
            return RedirectToAction("Index", new { employeeId = model.EmployeeId });
        }
    }
}

HelloMvc/Views/Shared/_EmployeeCard.cshtml
@model Employee

<div class="col-6">
    <div class="card mb-2">
        <div class="card-body">
            <h5 class="card-title">@Model.FirstName @Model.LastName</h5>
            @foreach (var vacation in Model.VacationRequests) {
                <ul class="list-group">
                    <li class="list-group-item mb-2">
                        <div>
                            @vacation.StartDate.ToString("d MMMM, yyyy") - @vacation.EndDate.ToString("d MMMM, yyyy")
                            <span class="text-success">
                                <strong> @((vacation.EndDate - vacation.StartDate).Days + 1) days</strong>
                            </span>
                        </div>

                        <div>
                            @vacation.Comment
                        </div>
                    </li>
                </ul>
            }

            <div class="text-end mt-3">
                <a asp-controller="Employees" asp-action="Edit" asp-route-id="@Model.EmployeeId" class="btn btn-primary">Edit User </a>
                <a asp-controller="Vacations" asp-action="Index" asp-route-EmployeeId="@Model.EmployeeId" class="btn btn-warning">Edit Vacations</a>
            </div>

        </div>
    </div>
</div>

HelloMvc/Views/Shared/_Layout-No-Menu.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HelloMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HelloMvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HelloMvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - HelloMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HelloMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HelloMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HelloMvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HelloMvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"  href="/Employees">Employees</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - HelloMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>